// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: proto/sqlserver/sqlserver-instance-management.proto
package sqlserverinstancemanagement

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// SQLServerInstanceManagementServiceName is the fully-qualified name of the SQLServerInstanceManagementService service.
	SQLServerInstanceManagementServiceName = "sqlserver.SQLServerInstanceManagementService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SQLServerInstanceManagementServiceCreateDBInstanceProcedure is the fully-qualified name of the SQLServerInstanceManagementService's CreateDBInstance RPC.
	SQLServerInstanceManagementServiceCreateDBInstanceProcedure = "/sqlserver.SQLServerInstanceManagementService/CreateDBInstance"
)

var (
	_ SQLServerInstanceManagementService = (*SQLServerInstanceManagementServiceImpl)(nil)
)

// SQLServerInstanceManagementService is a client for the sqlserver.SQLServerInstanceManagementService service.
type SQLServerInstanceManagementService interface {
	CreateDBInstance(ctx context.Context, req *CreateDBInstanceRequest, opts ...client.CallOption) (*CreateDBInstanceResponse, error)
}

// NewSQLServerInstanceManagementService constructs a client for the sqlserverinstancemanagement.SQLServerInstanceManagementService service.
func NewSQLServerInstanceManagementService(cli *client.Client, opts ...client.ReferenceOption) (SQLServerInstanceManagementService, error) {
	conn, err := cli.DialWithInfo("sqlserver.SQLServerInstanceManagementService", &SQLServerInstanceManagementService_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &SQLServerInstanceManagementServiceImpl{
		conn: conn,
	}, nil
}

func SetConsumerSQLServerInstanceManagementService(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &SQLServerInstanceManagementService_ClientInfo)
}

// SQLServerInstanceManagementServiceImpl implements SQLServerInstanceManagementService.
type SQLServerInstanceManagementServiceImpl struct {
	conn *client.Connection
}

func (c *SQLServerInstanceManagementServiceImpl) CreateDBInstance(ctx context.Context, req *CreateDBInstanceRequest, opts ...client.CallOption) (*CreateDBInstanceResponse, error) {
	resp := new(CreateDBInstanceResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "CreateDBInstance", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var SQLServerInstanceManagementService_ClientInfo = client.ClientInfo{
	InterfaceName: "sqlserver.SQLServerInstanceManagementService",
	MethodNames:   []string{"CreateDBInstance"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*SQLServerInstanceManagementServiceImpl)
		dubboCli.conn = conn
	},
}

// SQLServerInstanceManagementServiceHandler is an implementation of the sqlserver.SQLServerInstanceManagementService service.
type SQLServerInstanceManagementServiceHandler interface {
	CreateDBInstance(context.Context, *CreateDBInstanceRequest) (*CreateDBInstanceResponse, error)
}

func RegisterSQLServerInstanceManagementServiceHandler(srv *server.Server, hdlr SQLServerInstanceManagementServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &SQLServerInstanceManagementService_ServiceInfo, opts...)
}

func SetProviderSQLServerInstanceManagementService(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &SQLServerInstanceManagementService_ServiceInfo)
}

var SQLServerInstanceManagementService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "sqlserver.SQLServerInstanceManagementService",
	ServiceType:   (*SQLServerInstanceManagementServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "CreateDBInstance",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(CreateDBInstanceRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*CreateDBInstanceRequest)
				res, err := handler.(SQLServerInstanceManagementServiceHandler).CreateDBInstance(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
