system:
  bind_address: 127.0.0.1
  port: 20000

registry:
  service_name: mysql-instance-management
  type: zookeeper
  address: 192.168.2.88
  port: 2181

container_zone_config:
  address: https://192.168.2.99:8443

log_config:
