// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: proto/mysql/mysql-instance-management.proto
package mysqlinstancemanagement

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// MySQLInstanceManagementServiceName is the fully-qualified name of the MySQLInstanceManagementService service.
	MySQLInstanceManagementServiceName = "mysql.MySQLInstanceManagementService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MySQLInstanceManagementServiceCreateDBInstanceProcedure is the fully-qualified name of the MySQLInstanceManagementService's CreateDBInstance RPC.
	MySQLInstanceManagementServiceCreateDBInstanceProcedure = "/mysql.MySQLInstanceManagementService/CreateDBInstance"
)

var (
	_ MySQLInstanceManagementService = (*MySQLInstanceManagementServiceImpl)(nil)
)

// MySQLInstanceManagementService is a client for the mysql.MySQLInstanceManagementService service.
type MySQLInstanceManagementService interface {
	CreateDBInstance(ctx context.Context, req *CreateDBInstanceRequest, opts ...client.CallOption) (*CreateDBInstanceResponse, error)
}

// NewMySQLInstanceManagementService constructs a client for the mysqlinstancemanagement.MySQLInstanceManagementService service.
func NewMySQLInstanceManagementService(cli *client.Client, opts ...client.ReferenceOption) (MySQLInstanceManagementService, error) {
	conn, err := cli.DialWithInfo("mysql.MySQLInstanceManagementService", &MySQLInstanceManagementService_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &MySQLInstanceManagementServiceImpl{
		conn: conn,
	}, nil
}

func SetConsumerMySQLInstanceManagementService(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &MySQLInstanceManagementService_ClientInfo)
}

// MySQLInstanceManagementServiceImpl implements MySQLInstanceManagementService.
type MySQLInstanceManagementServiceImpl struct {
	conn *client.Connection
}

func (c *MySQLInstanceManagementServiceImpl) CreateDBInstance(ctx context.Context, req *CreateDBInstanceRequest, opts ...client.CallOption) (*CreateDBInstanceResponse, error) {
	resp := new(CreateDBInstanceResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "CreateDBInstance", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var MySQLInstanceManagementService_ClientInfo = client.ClientInfo{
	InterfaceName: "mysql.MySQLInstanceManagementService",
	MethodNames:   []string{"CreateDBInstance"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*MySQLInstanceManagementServiceImpl)
		dubboCli.conn = conn
	},
}

// MySQLInstanceManagementServiceHandler is an implementation of the mysql.MySQLInstanceManagementService service.
type MySQLInstanceManagementServiceHandler interface {
	CreateDBInstance(context.Context, *CreateDBInstanceRequest) (*CreateDBInstanceResponse, error)
}

func RegisterMySQLInstanceManagementServiceHandler(srv *server.Server, hdlr MySQLInstanceManagementServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &MySQLInstanceManagementService_ServiceInfo, opts...)
}

func SetProviderMySQLInstanceManagementService(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &MySQLInstanceManagementService_ServiceInfo)
}

var MySQLInstanceManagementService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "mysql.MySQLInstanceManagementService",
	ServiceType:   (*MySQLInstanceManagementServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "CreateDBInstance",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(CreateDBInstanceRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*CreateDBInstanceRequest)
				res, err := handler.(MySQLInstanceManagementServiceHandler).CreateDBInstance(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
