// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/mysql-instance-management.proto

package mysqlinstancemanagement

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDBInstanceRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InstanceName        string                 `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Engine              string                 `protobuf:"bytes,2,opt,name=engine,proto3" json:"engine,omitempty"`
	EngineVersion       string                 `protobuf:"bytes,3,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	InstanceClass       string                 `protobuf:"bytes,4,opt,name=instance_class,json=instanceClass,proto3" json:"instance_class,omitempty"`
	InstanceStorageGB   int32                  `protobuf:"varint,5,opt,name=instance_storage_g_b,json=instanceStorageGB,proto3" json:"instance_storage_g_b,omitempty"`
	ParameterGroup      string                 `protobuf:"bytes,6,opt,name=parameter_group,json=parameterGroup,proto3" json:"parameter_group,omitempty"`
	InstanceStorageType string                 `protobuf:"bytes,7,opt,name=instance_storage_type,json=instanceStorageType,proto3" json:"instance_storage_type,omitempty"`
	InstancePort        string                 `protobuf:"bytes,8,opt,name=instance_port,json=instancePort,proto3" json:"instance_port,omitempty"`
	StorageEncrypted    bool                   `protobuf:"varint,9,opt,name=storage_encrypted,json=storageEncrypted,proto3" json:"storage_encrypted,omitempty"`
	InstanceType        string                 `protobuf:"bytes,10,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateDBInstanceRequest) Reset() {
	*x = CreateDBInstanceRequest{}
	mi := &file_proto_mysql_instance_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDBInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDBInstanceRequest) ProtoMessage() {}

func (x *CreateDBInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mysql_instance_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDBInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateDBInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_mysql_instance_management_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDBInstanceRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *CreateDBInstanceRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *CreateDBInstanceRequest) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *CreateDBInstanceRequest) GetInstanceClass() string {
	if x != nil {
		return x.InstanceClass
	}
	return ""
}

func (x *CreateDBInstanceRequest) GetInstanceStorageGB() int32 {
	if x != nil {
		return x.InstanceStorageGB
	}
	return 0
}

func (x *CreateDBInstanceRequest) GetParameterGroup() string {
	if x != nil {
		return x.ParameterGroup
	}
	return ""
}

func (x *CreateDBInstanceRequest) GetInstanceStorageType() string {
	if x != nil {
		return x.InstanceStorageType
	}
	return ""
}

func (x *CreateDBInstanceRequest) GetInstancePort() string {
	if x != nil {
		return x.InstancePort
	}
	return ""
}

func (x *CreateDBInstanceRequest) GetStorageEncrypted() bool {
	if x != nil {
		return x.StorageEncrypted
	}
	return false
}

func (x *CreateDBInstanceRequest) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

type CreateDBInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDBInstanceResponse) Reset() {
	*x = CreateDBInstanceResponse{}
	mi := &file_proto_mysql_instance_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDBInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDBInstanceResponse) ProtoMessage() {}

func (x *CreateDBInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mysql_instance_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDBInstanceResponse.ProtoReflect.Descriptor instead.
func (*CreateDBInstanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_mysql_instance_management_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDBInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

var File_proto_mysql_instance_management_proto protoreflect.FileDescriptor

const file_proto_mysql_instance_management_proto_rawDesc = "" +
	"\n" +
	"%proto/mysql-instance-management.proto\x12\x05mysql\"\xa9\x03\n" +
	"\x17CreateDBInstanceRequest\x12#\n" +
	"\rinstance_name\x18\x01 \x01(\tR\finstanceName\x12\x16\n" +
	"\x06engine\x18\x02 \x01(\tR\x06engine\x12%\n" +
	"\x0eengine_version\x18\x03 \x01(\tR\rengineVersion\x12%\n" +
	"\x0einstance_class\x18\x04 \x01(\tR\rinstanceClass\x12/\n" +
	"\x14instance_storage_g_b\x18\x05 \x01(\x05R\x11instanceStorageGB\x12'\n" +
	"\x0fparameter_group\x18\x06 \x01(\tR\x0eparameterGroup\x122\n" +
	"\x15instance_storage_type\x18\a \x01(\tR\x13instanceStorageType\x12#\n" +
	"\rinstance_port\x18\b \x01(\tR\finstancePort\x12+\n" +
	"\x11storage_encrypted\x18\t \x01(\bR\x10storageEncrypted\x12#\n" +
	"\rinstance_type\x18\n" +
	" \x01(\tR\finstanceType\";\n" +
	"\x18CreateDBInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId2w\n" +
	"\x1eMySQLInstanceManagementService\x12U\n" +
	"\x10CreateDBInstance\x12\x1e.mysql.CreateDBInstanceRequest\x1a\x1f.mysql.CreateDBInstanceResponse\"\x00BeZcgithub.com/FixedShadow/jammy-cloud-database/mysql-instance-management/proto;mysqlinstancemanagementb\x06proto3"

var (
	file_proto_mysql_instance_management_proto_rawDescOnce sync.Once
	file_proto_mysql_instance_management_proto_rawDescData []byte
)

func file_proto_mysql_instance_management_proto_rawDescGZIP() []byte {
	file_proto_mysql_instance_management_proto_rawDescOnce.Do(func() {
		file_proto_mysql_instance_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mysql_instance_management_proto_rawDesc), len(file_proto_mysql_instance_management_proto_rawDesc)))
	})
	return file_proto_mysql_instance_management_proto_rawDescData
}

var file_proto_mysql_instance_management_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_mysql_instance_management_proto_goTypes = []any{
	(*CreateDBInstanceRequest)(nil),  // 0: mysql.CreateDBInstanceRequest
	(*CreateDBInstanceResponse)(nil), // 1: mysql.CreateDBInstanceResponse
}
var file_proto_mysql_instance_management_proto_depIdxs = []int32{
	0, // 0: mysql.MySQLInstanceManagementService.CreateDBInstance:input_type -> mysql.CreateDBInstanceRequest
	1, // 1: mysql.MySQLInstanceManagementService.CreateDBInstance:output_type -> mysql.CreateDBInstanceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mysql_instance_management_proto_init() }
func file_proto_mysql_instance_management_proto_init() {
	if File_proto_mysql_instance_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mysql_instance_management_proto_rawDesc), len(file_proto_mysql_instance_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mysql_instance_management_proto_goTypes,
		DependencyIndexes: file_proto_mysql_instance_management_proto_depIdxs,
		MessageInfos:      file_proto_mysql_instance_management_proto_msgTypes,
	}.Build()
	File_proto_mysql_instance_management_proto = out.File
	file_proto_mysql_instance_management_proto_goTypes = nil
	file_proto_mysql_instance_management_proto_depIdxs = nil
}
